// +build debug

// This file is generated by the vault-cli command line utility.
// It offers a easy way to embed binary resources into a go executable.
// DO NOT EDIT this file, it will be overwritten on the next run of the vault-cli utility.

package res

import (
	"fmt"
	"os"
	"path"
	"strings"
)

type debugLoader struct {
	base string
}

func (d debugLoader) Open(name string) (File, error) {
	if !strings.HasPrefix(name, "/") {
		name = "/" + name
	}

	return os.Open(getFullPath(d.base, name))
}

func getFullPath(b, p string) string {
	return path.Clean(fmt.Sprintf("%v/%v", b, path.Clean("/"+p)))
}

// NewReactLoader returns a new AssetLoader for the React resources.
func NewReactLoader() AssetLoader {
	return &debugLoader{base: "../webapp-frontend/build"}
}
